# Generated by Django 5.2.17 on 2026-08-12 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('subscription_expiry', 'Subscription expiry'), ('new_release', 'New release'), ('verification_result', 'Verification result'), ('monthly_payout', 'Monthly payout'), ('new_ticket', 'New ticket'), ('new_verification_request', 'New verification request')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
