# Generated by Django 5.2.16 on 2026-07-28 05:44

import apps.common.utils
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_playlists', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_stream_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('can_upload_avatar', models.BooleanField(default=False)),
                ('can_download', models.BooleanField(default=False)),
                ('early_access', models.BooleanField(default=False)),
                ('can_see_stats', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'monthly_price'),
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.UploadTo('albums/covers'))),
                ('release_type', models.CharField(choices=[('single', 'Single'), ('album', 'Album')], default='album', max_length=10)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.UploadTo('songs/covers'))),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=apps.common.utils.UploadTo('songs/audio'))),
                ('lyrics', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(blank=True, max_length=80)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('collaborators', models.JSONField(blank=True, default=list)),
                ('listeners_count', models.PositiveIntegerField(default=0)),
                ('streams_count', models.PositiveIntegerField(default=0)),
                ('is_released', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='catalog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
